version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "gha"
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "gomod"
    pull-request-branch-name:
      separator: "/"
